name: KBOT_CICD

on: push

jobs:
  ci:  
    name: CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Authenticate with Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set Google Cloud credentials environment variable
        run: echo "export GOOGLE_APPLICATION_CREDENTIALS=${{ steps.auth.outputs.credentials_file }}" >> $GITHUB_ENV
      - name: Run test
        run: make test
      - name: Authenticate Docker with GCR
        run: docker login -u _json_key --password-stdin https://gcr.io < $GOOGLE_APPLICATION_CREDENTIALS
      - name: Authenticate GHCR
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin    
      - name: Build&Push
        env:
          APP: "kbot"  
          REGISTRY: ghcr.io/${{ github.repository_owner }}
        run: |
          docker build -t $REGISTRY/$APP .
          docker push $REGISTRY/$APP
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)-linux-amd64" >> $GITHUB_ENV
      
      - uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "update version $VERSION"    
          git push

